---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: apache
  namespace: apache
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: apache
  chart:
    git: ssh://git@github.com:praveensams/helm
    ref: master
    path: charts/apache
